# languages.py - Urdu/English translations

TRANSLATIONS = {
    'en': {
        # General
        'settings': 'Settings',
        'general': 'General',
        'profile': 'Profile',
        'invoice': 'Invoice',
        'payments': 'Payments',
        'backup': 'Backup',
        'users': 'Users',
        'theme': 'Theme',
        'home': 'Home',
        'dashboard': 'Dashboard',
        'save': 'Save',
        'cancel': 'Cancel',
        'delete': 'Delete',
        'edit': 'Edit',
        'update': 'Update',
        'create': 'Create',
        'search': 'Search',
        'actions': 'Actions',
        'showing': 'Showing',
        'backups': 'backups',
        'all': 'All',
        'today': 'Today',
        'this_week': 'This Week',
        'this_month': 'This Month',
        'custom_range': 'Custom Range',
        'from': 'From',
        'to': 'to',
        'apply': 'Apply',
        'clear': 'Clear',
        'total': 'Total',
        'manual': 'Manual',
        'auto': 'Auto',
        'system': 'System',
        'never': 'Never',
        'create_backup': 'Create Backup',
        'excel_export': 'Excel Export Available',
        'excel': 'Excel',
        'download_db': 'Download DB',
        'delete_backup': 'Delete Backup',
        'backup_information': 'Backup Information',
        'auto_backup': 'Auto Backup',
        'backup_statistics': 'Backup Statistics',
        'total_backups': 'Total Backups',
        'last_backup': 'Last Backup',
        'export_guide': 'Export Guide',
        'how_to_export': 'How to Export',
        'step1': 'Click "Create Backup" to create a new backup',
        'step2': 'Find your backup in the list below',
        'step3': 'Click the Green "Excel" button',
        'step4': 'File will download as .xlsx format',
        'step5': 'Open in Excel or Google Sheets',
        'shop_name': 'Shop Name',
        'shop_address': 'Shop Address',
        'phone_number': 'Phone Number',
        'email': 'Email',
        'gst_number': 'GST / NTN Number',
        'currency': 'Currency',
        'date_format': 'Date Format',
        'time_format': 'Time Format',
        'language_label': 'Language',
        'business_settings': 'Business Settings',
        'default_tax_rate': 'Default Tax Rate (%)',
        'default_discount': 'Default Discount (%)',
        'default_shipping': 'Default Shipping (PKR)',
        'invoice_footer': 'Invoice Footer Text',
        'maintenance_mode': 'Maintenance Mode',
        'enable_maintenance': 'Enable to show maintenance page to non-admin users',
        'save_general': 'Save General Settings',
        'reset_defaults': 'Reset Defaults',
        'this_will_appear': 'This will appear on invoices and receipts',
        'enter_shop_name': 'Enter shop name',
        'enter_shop_address': 'Enter shop address',
        'enter_phone': '03XX-XXXXXXX',
        'enter_email': 'shop@email.com',
        'enter_gst': 'GST-XXXXX',
        'full_name': 'Full Name',
        'username': 'Username',
        'username_cannot_change': 'Username cannot be changed',
        'role': 'Role',
        'role_managed': 'Role managed by administrator',
        'change_password': 'Change Password',
        'leave_blank': 'Leave blank if you don\'t want to change password',
        'new_password': 'New Password',
        'confirm_password': 'Confirm Password',
        'enter_new_password': 'Enter new password',
        'confirm_new_password': 'Confirm new password',
        'update_profile': 'Update Profile',
        'enter_full_name': 'Enter full name',
        'enter_email_address': 'Enter email',
        'invoice_prefix': 'Invoice Prefix',
        'next_invoice': 'Next Invoice Number',
        'logo_position': 'Logo Position',
        'left': 'Left',
        'center': 'Center',
        'right': 'Right',
        'receipt_footer': 'Receipt Footer Message',
        'show_barcode': 'Show Barcode on Receipts',
        'save_invoice': 'Save Invoice Settings',
        'enter_invoice_prefix': 'e.g., INV-',
        'default_payment_method': 'Default Payment Method',
        'payment_due_days': 'Payment Due Days',
        'default_days': 'Default days before payment becomes overdue',
        'mobile_wallet_settings': 'Mobile Wallet Settings',
        'jazzcash_number': 'JazzCash Number',
        'easypaisa_number': 'EasyPaisa Number',
        'bank_account': 'Bank Account',
        'enter_account_number': 'Account #',
        'save_payment': 'Save Payment Settings',
        'cash': 'Cash',
        'card': 'Card',
        'online_transfer': 'Online Transfer',
        'due': 'Due',
        'auto_backup_frequency': 'Auto Backup Frequency',
        'daily': 'Daily',
        'weekly': 'Weekly',
        'monthly': 'Monthly',
        'disabled': 'Disabled',
        'backup_time': 'Backup Time',
        'keep_backups': 'Keep Backups',
        'last_5': 'Last 5',
        'last_10': 'Last 10',
        'last_20': 'Last 20',
        'last_50': 'Last 50',
        'keep_all': 'Keep All',
        'auto_export_excel': 'Auto Export to Excel on Backup',
        'auto_export_desc': 'Automatically create Excel file when backup is created',
        'save_backup': 'Save Backup Settings',
        'older_deleted': 'Auto backups to keep (older will be deleted)',
        'user_management': 'User Management',
        'add_user': 'Add User',
        'status': 'Status',
        'active': 'Active',
        'inactive': 'Inactive',
        'last_login': 'Last Login',
        'theme_mode': 'Theme Mode',
        'light': 'Light',
        'dark': 'Dark',
        'color_theme': 'Color Theme',
        'click_to_change': 'Click to change color theme',
        'save_theme': 'Save Theme',
        'backup_info': 'Backup Information',
        'excel_export_available': 'Click the "Excel" button next to any backup to export all data as an Excel file. Each table will be in a separate sheet.',
        'backup_stats': 'Backup Statistics',
        'total_backups_count': 'Total Backups',
        'last_backup_date': 'Last Backup',
        'excel_export_label': 'Excel Export Available',
        'filter_backups': 'Filter Backups',
        'quick_filter': 'Quick Filter',
        'custom_date_range': 'Custom Date Range',
        'backup_stats_label': 'Backup Stats',
        'all_backups': 'All backups',
        'todays_backups': 'Today\'s backups',
        'this_weeks_backups': 'This week\'s backups',
        'this_months_backups': 'This month\'s backups',
        'showing_backups': 'Showing',
        'no_backups_found': 'No backups found',
        'create_first_backup': 'Click "Create Backup" to create your first backup.',
        'export_backup_btn': 'Export as Excel (Best for viewing)',
        'download_db_btn': 'Download DB file',
        'delete_backup_btn': 'Delete Backup',
        'delete_confirm': 'Delete Backup?',
        'delete_confirm_text': 'This action cannot be undone.',
        'yes_delete': 'Yes, delete it!',
        'settings_saved': 'Settings saved successfully!',
        'profile_updated': 'Profile updated successfully!',
        'preferences_updated': 'Preferences updated successfully!',
        'language_changed_english': 'Language changed to English',
        'language_changed_urdu': 'Language changed to Urdu',
        'backup_created': 'Backup created successfully!',
        'backup_deleted': 'Backup deleted successfully',
        'error_creating_backup': 'Error creating backup',
        'backup_file_not_found': 'Backup file not found',
        'no_tables_found': 'No tables found in backup',
        'error_exporting_backup': 'Error exporting backup',
        'filter_loading': 'Loading backups...',
        'showing_count': 'Showing {count} backups',
        'error_loading_backups': 'Error loading backups',
        'please_select_date': 'Please select a date range',
        'warning': 'Warning',
        'success': 'Success',
        'error': 'Error',
        'info': 'Info',
        'excel_file_saved': 'Excel file saved successfully',
        'file_deleted': 'File deleted successfully',
        'file_not_found': 'File not found',
    },
    'ur': {
        'settings': 'ترتیبات',
        'general': 'عمومی',
        'profile': 'پروفائل',
        'invoice': 'انوائس',
        'payments': 'ادائیگیاں',
        'backup': 'بیک اپ',
        'users': 'صارفین',
        'theme': 'تھیم',
        'home': 'ہوم',
        'dashboard': 'ڈیش بورڈ',
        'save': 'محفوظ کریں',
        'cancel': 'منسوخ کریں',
        'delete': 'حذف کریں',
        'edit': 'ترمیم کریں',
        'update': 'اپ ڈیٹ کریں',
        'create': 'بنائیں',
        'search': 'تلاش کریں',
        'actions': 'اعمال',
        'showing': 'دکھا رہا ہے',
        'backups': 'بیک اپ',
        'all': 'سب',
        'today': 'آج',
        'this_week': 'اس ہفتے',
        'this_month': 'اس مہینے',
        'custom_range': 'اپنی تاریخ',
        'from': 'سے',
        'to': 'تک',
        'apply': 'لگائیں',
        'clear': 'صاف کریں',
        'total': 'کل',
        'manual': 'دستی',
        'auto': 'خودکار',
        'system': 'سسٹم',
        'never': 'کبھی نہیں',
        'create_backup': 'بیک اپ بنائیں',
        'excel_export': 'ایکسل ایکسپورٹ دستیاب',
        'excel': 'ایکسل',
        'download_db': 'ڈی بی ڈاؤن لوڈ',
        'delete_backup': 'بیک اپ حذف کریں',
        'backup_information': 'بیک اپ کی معلومات',
        'auto_backup': 'خودکار بیک اپ',
        'backup_statistics': 'بیک اپ کے اعداد و شمار',
        'total_backups': 'کل بیک اپ',
        'last_backup': 'آخری بیک اپ',
        'export_guide': 'ایکسپورٹ گائیڈ',
        'how_to_export': 'ایکسپورٹ کیسے کریں',
        'step1': '"بیک اپ بنائیں" پر کلک کریں',
        'step2': 'نیچے دی گئی فہرست میں اپنا بیک اپ تلاش کریں',
        'step3': 'سبز "ایکسل" بٹن پر کلک کریں',
        'step4': 'فائل .xlsx فارمیٹ میں ڈاؤن لوڈ ہو گی',
        'step5': 'ایکسل یا گوگل شیٹس میں کھولیں',
        'shop_name': 'دکان کا نام',
        'shop_address': 'دکان کا پتہ',
        'phone_number': 'فون نمبر',
        'email': 'ای میل',
        'gst_number': 'جی ایس ٹی / این ٹی این نمبر',
        'currency': 'کرنسی',
        'date_format': 'تاریخ کا فارمیٹ',
        'time_format': 'وقت کا فارمیٹ',
        'language_label': 'زبان',
        'business_settings': 'کاروباری ترتیبات',
        'default_tax_rate': 'ڈیفالٹ ٹیکس ریٹ (%)',
        'default_discount': 'ڈیفالٹ ڈسکاؤنٹ (%)',
        'default_shipping': 'ڈیفالٹ شپنگ (PKR)',
        'invoice_footer': 'انوائس فوٹر ٹیکسٹ',
        'maintenance_mode': 'مینٹیننس موڈ',
        'enable_maintenance': 'غیر ایڈمن صارفین کو مینٹیننس پیج دکھانے کے لیے فعال کریں',
        'save_general': 'عمومی ترتیبات محفوظ کریں',
        'reset_defaults': 'ڈیفالٹس ری سیٹ کریں',
        'this_will_appear': 'یہ انوائس اور رسیدوں پر ظاہر ہو گا',
        'enter_shop_name': 'دکان کا نام درج کریں',
        'enter_shop_address': 'دکان کا پتہ درج کریں',
        'enter_phone': '03XX-XXXXXXX',
        'enter_email': 'shop@email.com',
        'enter_gst': 'GST-XXXXX',
        'full_name': 'پورا نام',
        'username': 'صارف نام',
        'username_cannot_change': 'صارف نام تبدیل نہیں کیا جا سکتا',
        'role': 'کردار',
        'role_managed': 'کردار منتظم کے ذریعے منظم کیا جاتا ہے',
        'change_password': 'پاس ورڈ تبدیل کریں',
        'leave_blank': 'اگر پاس ورڈ تبدیل نہیں کرنا تو خالی چھوڑ دیں',
        'new_password': 'نیا پاس ورڈ',
        'confirm_password': 'پاس ورڈ کی تصدیق کریں',
        'enter_new_password': 'نیا پاس ورڈ درج کریں',
        'confirm_new_password': 'نیا پاس ورڈ کی تصدیق کریں',
        'update_profile': 'پروفائل اپ ڈیٹ کریں',
        'enter_full_name': 'پورا نام درج کریں',
        'enter_email_address': 'ای میل درج کریں',
        'invoice_prefix': 'انوائس کا سابقہ',
        'next_invoice': 'اگلا انوائس نمبر',
        'logo_position': 'لوگو کی پوزیشن',
        'left': 'بائیں',
        'center': 'مرکز',
        'right': 'دائیں',
        'receipt_footer': 'رسیپٹ فوٹر پیغام',
        'show_barcode': 'رسیپٹس پر بارکوڈ دکھائیں',
        'save_invoice': 'انوائس ترتیبات محفوظ کریں',
        'enter_invoice_prefix': 'مثال: INV-',
        'default_payment_method': 'ڈیفالٹ ادائیگی کا طریقہ',
        'payment_due_days': 'ادائیگی کی مقررہ دن',
        'default_days': 'ادائیگی کی مقررہ تاریخ سے پہلے ڈیفالٹ دن',
        'mobile_wallet_settings': 'موبائل والیٹ ترتیبات',
        'jazzcash_number': 'جازکیش نمبر',
        'easypaisa_number': 'ایزی پیسہ نمبر',
        'bank_account': 'بینک اکاؤنٹ',
        'enter_account_number': 'اکاؤنٹ نمبر',
        'save_payment': 'ادائیگی ترتیبات محفوظ کریں',
        'cash': 'نقد',
        'card': 'کارڈ',
        'online_transfer': 'آن لائن ٹرانسفر',
        'due': 'بقایا',
        'auto_backup_frequency': 'خودکار بیک اپ فریکوئنسی',
        'daily': 'روزانہ',
        'weekly': 'ہفتہ وار',
        'monthly': 'ماہانہ',
        'disabled': 'غیر فعال',
        'backup_time': 'بیک اپ کا وقت',
        'keep_backups': 'بیک اپ رکھیں',
        'last_5': 'آخری 5',
        'last_10': 'آخری 10',
        'last_20': 'آخری 20',
        'last_50': 'آخری 50',
        'keep_all': 'سب رکھیں',
        'auto_export_excel': 'بیک اپ پر خودکار ایکسل ایکسپورٹ',
        'auto_export_desc': 'بیک اپ بننے پر خودکار طور پر ایکسل فائل بنائیں',
        'save_backup': 'بیک اپ ترتیبات محفوظ کریں',
        'older_deleted': 'خودکار بیک اپ رکھیں (پرانی ڈیلیٹ ہو جائیں گی)',
        'user_management': 'صارفین کا انتظام',
        'add_user': 'صارف شامل کریں',
        'status': 'حالت',
        'active': 'فعال',
        'inactive': 'غیر فعال',
        'last_login': 'آخری لاگ ان',
        'theme_mode': 'تھیم موڈ',
        'light': 'روشن',
        'dark': 'اندھیرا',
        'color_theme': 'رنگ تھیم',
        'click_to_change': 'رنگ تھیم تبدیل کرنے کے لیے کلک کریں',
        'save_theme': 'تھیم محفوظ کریں',
        'backup_info': 'بیک اپ کی معلومات',
        'excel_export_available': 'کسی بھی بیک اپ کے ساتھ "ایکسل" بٹن پر کلک کریں تاکہ تمام ڈیٹا ایکسل فائل کے طور پر ایکسپورٹ ہو۔ ہر ٹیبل الگ شیٹ میں ہو گی۔',
        'backup_stats': 'بیک اپ کے اعداد و شمار',
        'total_backups_count': 'کل بیک اپ',
        'last_backup_date': 'آخری بیک اپ',
        'excel_export_label': 'ایکسل ایکسپورٹ دستیاب',
        'filter_backups': 'بیک اپ فلٹر کریں',
        'quick_filter': 'فوری فلٹر',
        'custom_date_range': 'اپنی تاریخ',
        'backup_stats_label': 'بیک اپ کے اعداد و شمار',
        'all_backups': 'تمام بیک اپ',
        'todays_backups': 'آج کے بیک اپ',
        'this_weeks_backups': 'اس ہفتے کے بیک اپ',
        'this_months_backups': 'اس مہینے کے بیک اپ',
        'showing_backups': 'دکھا رہا ہے',
        'no_backups_found': 'کوئی بیک اپ نہیں ملا',
        'create_first_backup': 'اپنا پہلا بیک اپ بنانے کے لیے "بیک اپ بنائیں" پر کلک کریں۔',
        'export_backup_btn': 'ایکسل کے طور پر ایکسپورٹ کریں (دیکھنے کے لیے بہترین)',
        'download_db_btn': 'ڈی بی فائل ڈاؤن لوڈ کریں',
        'delete_backup_btn': 'بیک اپ حذف کریں',
        'delete_confirm': 'بیک اپ حذف کریں؟',
        'delete_confirm_text': 'یہ عمل واپس نہیں کیا جا سکتا۔',
        'yes_delete': 'ہاں، حذف کریں!',
        'settings_saved': 'ترتیبات کامیابی سے محفوظ ہو گئیں!',
        'profile_updated': 'پروفائل کامیابی سے اپ ڈیٹ ہو گیا!',
        'preferences_updated': 'ترجیحات کامیابی سے اپ ڈیٹ ہو گئیں!',
        'language_changed_english': 'زبان انگریزی میں تبدیل ہو گئی',
        'language_changed_urdu': 'زبان اردو میں تبدیل ہو گئی',
        'backup_created': 'بیک اپ کامیابی سے بن گیا!',
        'backup_deleted': 'بیک اپ کامیابی سے حذف ہو گیا',
        'error_creating_backup': 'بیک اپ بنانے میں خرابی',
        'backup_file_not_found': 'بیک اپ فائل نہیں ملی',
        'no_tables_found': 'بیک اپ میں کوئی ٹیبل نہیں ملا',
        'error_exporting_backup': 'بیک اپ ایکسپورٹ کرنے میں خرابی',
        'filter_loading': 'بیک اپ لوڈ ہو رہے ہیں...',
        'showing_count': '{count} بیک اپ دکھا رہا ہے',
        'error_loading_backups': 'بیک اپ لوڈ کرنے میں خرابی',
        'please_select_date': 'براہ کرم تاریخ کی حد منتخب کریں',
        'warning': 'انتباہ',
        'success': 'کامیاب',
        'error': 'خرابی',
        'info': 'معلومات',
        'excel_file_saved': 'ایکسل فائل کامیابی سے محفوظ ہو گئی',
        'file_deleted': 'فائل کامیابی سے حذف ہو گئی',
        'file_not_found': 'فائل نہیں ملی',
    }
}

def t(key, lang=None):
    """Get translation for a key"""
    from flask import session
    if lang is None:
        lang = session.get('language', 'en')
    return TRANSLATIONS.get(lang, TRANSLATIONS['en']).get(key, key)